#!/usr/bin/env bash

set -e

PROJECT_ROOT="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
VENDOR_DIRECTORY=$PROJECT_ROOT/vendor
ANDROID_SDK_ARTIFACT=android-sdk_r21.1-macosx.zip
ANDROID_SDK_DIRECTORY=$VENDOR_DIRECTORY/android-sdk-macosx

cd $PROJECT_ROOT

wget http://dl.google.com/android/$ANDROID_SDK_ARTIFACT
unzip -d $VENDOR_DIRECTORY $ANDROID_SDK_ARTIFACT
rm -rf $ANDROID_SDK_ARTIFACT

export ANDROID_HOME=$ANDROID_SDK_DIRECTORY
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
android update sdk --no-ui --force --filter platform-tools,extra-android-support,android-17,sysimg-17,extra-google-google_play_services

cp vendor/gms-mvn/gms-mvn-install.sh $ANDROID_SDK_DIRECTORY/extras/google/google_play_services/libproject/google-play-services_lib/
cd $ANDROID_SDK_DIRECTORY/extras/google/google_play_services/libproject/google-play-services_lib/
./gms-mvn-install.sh
cd $PROJECT_ROOT

echo no | android create avd -n emulator -t android-17 --skin WVGA800 --force --abi armeabi-v7a

gem install calabash-android